trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '18'

steps:
- task: UseNode@1
  inputs:
    version: '$(nodeVersion)'

- script: |
    npm ci
    npm run build
  displayName: 'Install and build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'out'
    ArtifactName: 'site'
    publishLocation: 'Container'
