import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google"; // تأكد من وجود Inter هنا
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// **الخط الجديد: Inter (للعناوين)**
const interHeading = Inter({
  subsets: ["latin"],
  weight: ['400', '600', '700'], // استيراد الأوزان 600 (Semibold) و 700 (Bold)
  variable: "--font-heading", // تعريف متغير CSS
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // إضافة متغير خط Inter إلى الكلاسات المتاحة
        className={`${geistSans.variable} ${geistMono.variable} ${interHeading.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}