import type { Metadata } from "next";
// تم تغيير الاستيراد هنا
import { Geist, Geist_Mono, Inter } from "next/font/google"; 
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// **الخط الجديد: Inter (سيستخدم للعناوين)**
const interHeading = Inter({
  subsets: ["latin"],
  weight: ['400', '700', '800', '900'], // استيراد الأوزان المطلوبة
  variable: "--font-heading", // تعريف متغير CSS جديد
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // تم إضافة المتغير الجديد إلى الكلاسات المتاحة
        className={`${geistSans.variable} ${geistMono.variable} ${interHeading.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}